# Generated by Django 4.1.1 on 2022-09-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='make',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='year',
            new_name='inventory_quantity',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='model',
            new_name='title',
        ),
    ]
